
---

#####################################################################
# general configuration, not tied to any specific course
# point person: undergraduate committee
#####################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: Update repositories cache and update all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

#####################################################################
# CPSC 120-121-131 official environment
# point person: undergraduate committee
#####################################################################

- hosts: all
  remote_user: root
  vars:
    login: student
  tasks:

    - name: clang toolchain
      apt:
        pkg:
          - build-essential
          - clang
          - clang-tidy
          - clang-format
          - lldb

    - name: g++ 9 compiler
      apt:
        pkg:
          - build-essential
          - gcc-9
          - g++-9
          - gdb

    - name: Google Test Package Install
      apt:
        pkg:
          - libgtest-dev
          - build-essential
          - cmake
          - clang
          - gcc-9
          - g++-9

    - name: Google Test Library Build
      shell: |
        BUILDDIR="/tmp/gtestbuild.$$"
        DESTROOT="/usr/local/"
        mkdir -p ${BUILDDIR}
        cd ${BUILDDIR}
        cmake -DCMAKE_BUILD_TYPE=RELEASE /usr/src/gtest/
        make
        install -o root -g root -m 644 libgtest.a ${DESTROOT}/lib
        install -o root -g root -m 644 libgtest_main.a ${DESTROOT}/lib


#####################################################################
# cleanup
# point person: undergraduate committee
#####################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: apt clean
      command: apt clean

...
