
---

#####################################################################
# general configuration, not tied to any specific course
# point person: undergraduate committee
#####################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Kitchen sink packages
      apt:
        pkg:
          - curl
          - enscript
          - gpg
          - openssh-client
          - openssh-server
          - synaptic
          - vim
          - libreadline-dev
          - manpages-posix
          - manpages-posix-dev
          - glibc-doc
          - nfs-common
          - graphicsmagick
          - libgraphicsmagick++1-dev
          - doxygen
          - valgrind
          #- a2ps
          #- chromium-browser
          #- dkms
          #- emacs
          #- gthumb
          #- seahorse
          #- vim-gtk3

#####################################################################
# CPSC 120-121-131 official environment
# point person: undergraduate committee
#####################################################################

- hosts: all
  remote_user: root
  vars:
    login: student
  tasks:

    - name: Clang toolchain
      apt:
        pkg:
          - build-essential
          - clang
          - clang-tidy
          - clang-format
          - lldb

    - name: G++ compiler (default version for target Ubuntu release)
      apt:
        pkg:
          - build-essential
          - gcc
          - g++
          - gdb

    - name: Source code control
      apt:
        pkg:
          - git
          - subversion

    - name: Google Test and Google Mock
      apt:
        pkg:
          - libgtest-dev
          - libgmock-dev
          - cmake

    - name: Google Mock Library Build (builds Google Test Library as a dependency)
      shell: |
        BUILDDIR="/tmp/gmockbuild.$$"
        DESTROOT="/usr/local/"
        mkdir -p ${BUILDDIR}
        cd ${BUILDDIR}
        cmake -DCMAKE_BUILD_TYPE=RELEASE /usr/src/googletest/googlemock
        make
        mkdir -p ${DESTROOT}/lib
        install -o root -g root -m 644 ./lib/libgtest.a ${DESTROOT}/lib
        install -o root -g root -m 644 ./lib/libgtest_main.a ${DESTROOT}/lib
        install -o root -g root -m 644 ./lib/libgmock.a ${DESTROOT}/lib
        install -o root -g root -m 644 ./lib/libgmock_main.a ${DESTROOT}/lib

    - name: additional C++ libraries and tools
      apt:
        pkg:
          - autoconf
          - automake
          - libc++-dev
          - libc++abi-dev
          - nlohmann-json3-dev
          - libyaml-cpp-dev
          #- cscope
          #- libboost-all-dev
          #- libfccp-dev
          #- libsqlite3-dev
          #- libssl-dev
          #- meld
          #- sqlite3
          #- valgrind


#####################################################################
# CPSC 240
# point person: Floyd Holliday
#####################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: 240 assembly environment
      apt:
        pkg:
          - intel2gas
          - nasm

#####################################################################
# GitHub's gh utility
# point person: Michael Shafae
#####################################################################

    - name: Prerequisites for GitHub's gh
      apt:
        pkg:
          - dirmngr
          - software-properties-common

    - name: gh client distribution URI as package source (i386, amd64, arm64)
      shell: |
        apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        apt-add-repository https://cli.github.com/packages
    
    - name: GitHub gh
      apt:
        pkg:
          - gh

#####################################################################
# cleanup
# point person: undergraduate committee
#####################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: apt clean
      command: apt clean

...
