
---

###############################################################################
# general configuration, not tied to any specific course
# point person: undergraduate committee
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: Update repositories cache and update all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: kitchen sink packages
      apt: name={{item}} state=present
      with_items:
        - a2ps
        #- cifs-utils
        - chromium-browser
        - curl
        #- default-jdk
        - dkms
        #- eclipse
        - emacs
        #- gnupg2
        #- pgpgpg
        - gpg
        - graphviz
        - gthumb
        #- lynx
        #- octave
        - openssh-client
        - openssh-server
        #- racket
        - seahorse
        - stow
        - synaptic
        - vagrant
        - vim
        - xfce4-goodies
        - xfce4-weather-plugin

###############################################################################
# CPSC 120-121-131 official environment
# point person: undergraduate committee
###############################################################################

- hosts: all
  remote_user: root
  vars:
    login: student
  tasks:

    - name: clang toolchain
      apt: name={{item}} state=present
      with_items:
        - build-essential
        - clang
        - clang-tidy
        - clang-format

    - name: g++ 9 compiler
      apt: name={{item}} state=present
      with_items:
        - build-essential
        - gcc-9
        - g++-9

    - name: gdb debugger
      apt: name=gdb state=present

    - name: source code control
      apt: name={{item}} state=present
      with_items:
        - git
        - subversion

    - name: googletest dependencies
      apt: name={{item}} state=present
      with_items:
        - build-essential
        - cmake

    - name: googletest clone
      git:
        repo: https://github.com/google/googletest.git
        dest: /tmp/googletest

    - name: googletest cmake
      shell: cmake CMakeLists.txt
      args:
        chdir: /tmp/googletest

    - name: googletest make
      make:
        chdir: /tmp/googletest

    - name: googletest install
      shell: |
        cp -r googletest/include/. /usr/include
        cp -r googlemock/include/. /usr/include
        cp lib/*.a /usr/lib
      args:
        chdir: /tmp/googletest

    - name: googletest clean
      file:
        state: absent
        path: /tmp/googletest

    - name: media computation tools
      apt: name={{item}} state=present
      with_items:
        - audacity
        - blender
        - gimp
        - imagemagick
        - sox
        - vlc

    - name: additional C++ libraries and tools
      apt: name={{item}} state=present
      with_items:
        - autoconf
        - automake
        - cscope
        - gobjc++
        - gobjc
        - libboost-all-dev
        - libfccp-dev
        - libglib2.0-dev
        - libgtkmm-3.0-dev
        - libsdl2-dev
        - libsdl2-gfx-dev
        - libsqlite3-dev
        - libssl-dev
        - lldb
        - meld
        # Not available for Ubuntu 16.04 LTS
        - nlohmann-json-dev
        - scons
        - sqlite3
        - valgrind

###############################################################################
# Mikhail Gofman's Packages
# point person: Mikhail Gofman
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: Mikhail Gofman's Packages
      apt: name={{item}} state=present
      with_items:
        - tmate

###############################################################################
# CPSC 223J
# point person: Floyd Holliday
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: 223J Java environment
      apt: name={{item}} state=present
      with_items:
        - geany
        - gthumb
        - netbeans
        - openjdk-8-jdk
        - openjdk-8-jre

###############################################################################
# CPSC 223P
# point person: Michael Shafae
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: 223P Python environment
      apt: name={{item}} state=present
      with_items:
        - python
        - python-dev
        - python-pip
        - python-virtualenv
        - python3
        - python3-dev
        - python3-pip
        - virtualenvwrapper

###############################################################################
# CPSC 223N
# point person: Floyd Holliday
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: 223N C# environment
      apt: name={{item}} state=present
      with_items:
        - mono-complete
        - netbeans

###############################################################################
# CPSC 240
# point person: Floyd Holliday
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: 240 assembly environment
      apt: name={{item}} state=present
      with_items:
        - intel2gas
        - nasm

###############################################################################
# CPSC 351
# point person: Michael Shafae
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: 351 libraries
      apt: name={{item}} state=present
      with_items:
        - libreadline-dev
        - manpages-posix
        - manpages-posix-dev
        - glibc-doc

###############################################################################
# CPSC 481
# point person: Paul Salvador Inventado
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: 481 Languages possibly used for AI projects
      apt: name={{item}} state=present
      with_items:
        - swi-prolog-x
        - swi-prolog-nox
        - sbcl
    - name: Eclipse installation
      unarchive:
        src: http://eclipse.bluemix.net/packages/2019-06/data/eclipse-java-2019-06-R-linux-gtk-x86_64.tar.gz
        dest: /opt
        remote_src: yes

    - name: Link Eclipse executable
      file:
        state: link
        src: /opt/eclipse/eclipse
        dest: /usr/local/bin/eclipse

#    - name: Create Eclipse menu item
#      copy:
#        src: eclipse.desktop
#        dest: /usr/share/applications/eclipse.desktop

###############################################################################
# CPSC 484
# point person: Michael Shafae, Kevin Wortman
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: 484 graphics environment
      apt: name={{item}} state=present
      with_items:
        - freeglut3-dev
        - libfreeimage-dev
        - libglu1-mesa-dev
        - libglew-dev
        - libgl1-mesa-dev
        - libopenctm-dev
        - libx11-dev
        - libxi-dev
        - libxrandr-dev
        - mesa-utils
        - mesa-utils-extra
        - openctm-tools
        - openctm-doc
        - python-openctm

###############################################################################
# cleanup
# point person: undergraduate committee
###############################################################################

- hosts: all
  remote_user: root
  tasks:

    - name: apt clean
      command: apt clean

...
